export const ROUTES = {
    HOME: '/',
    REQUESTS: '/requests',
    DATABASE: '/database',
    TASKS: '/tasks',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    RESET_PASSWORD: '/auth/reset-password',
    NEW_PASSWORD: '/auth/new-password',
    CHANGE_PASSWORD: '/profile/change-password',
    PERSONAL_PROFILE: '/profile',
    MAIN_PAGE: '/main-page',
    CONTACT: '/contact',
    COMPARE_RESUMES: '/compare-resumes',
    VACANCIES_LIST: '/vacancies',
    VACANCY_DESC: '/vacancies/:id',
    APPLICATIONS: '/:userId/applications',
};
