export const IT_SKILLS = [
    // Программирование и разработка
    'JavaScript',
    'TypeScript',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Express.js',
    'NestJS',
    'Python',
    'Django',
    'Flask',
    'Java',
    'Spring Boot',
    'Kotlin',
    'C#',
    '.NET',
    'ASP.NET',
    'PHP',
    'Laravel',
    'Symfony',
    'Ruby',
    'Ruby on Rails',
    'Go',
    'Rust',
    'Swift',
    'Objective-C',
    'Dart',
    'Flutter',
    'HTML',
    'CSS',
    'SASS/SCSS',
    'Tailwind CSS',
    'Bootstrap',
    'Material-UI',
    'Redux',
    'MobX',
    'GraphQL',
    'REST API',
    'WebSocket',
    'Docker',
    'Kubernetes',
    'AWS',
    'Google Cloud',
    'Azure',
    'Firebase',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'SQLite',
    'Redis',
    'Elasticsearch',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'CI/CD',
    'Jenkins',
    'GitHub Actions',
    'Linux',
    'Bash',
    'Shell Scripting',

    // Управление проектами
    'Agile',
    'Scrum',
    'Kanban',
    'Jira',
    'Confluence',
    'Trello',
    'Asana',
    'Project Management',
    'Product Management',
    'Roadmapping',
    'Risk Management',
    'Stakeholder Management',

    // Дизайн и UX/UI
    'Figma',
    'Adobe XD',
    'Sketch',
    'InVision',
    'Photoshop',
    'Illustrator',
    'After Effects',
    'Premiere Pro',
    'UI Design',
    'UX Design',
    'Wireframing',
    'Prototyping',
    'User Research',
    'Usability Testing',
    'Interaction Design',
    'Visual Design',
    'Design Systems',
    'Responsive Design',
    'Motion Design',
    '3D Modeling',
    'Blender',
    'Cinema 4D',
    'Typography',
    'Color Theory',

    // Маркетинг
    'Digital Marketing',
    'SEO',
    'SEM',
    'Google Analytics',
    'Google Ads',
    'Facebook Ads',
    'Instagram Marketing',
    'Content Marketing',
    'Email Marketing',
    'Social Media Marketing',
    'Influencer Marketing',
    'Affiliate Marketing',
    'PPC',
    'Copywriting',
    'Branding',
    'Market Research',
    'Customer Journey Mapping',
    'CRM',
    'HubSpot',
    'Salesforce',
    'Marketing Automation',
    'A/B Testing',
    'Growth Hacking',
    'Public Relations',
    'Event Marketing',

    // Аналитика и Data Science
    'Data Analysis',
    'Data Visualization',
    'Tableau',
    'Power BI',
    'Excel',
    'SQL',
    'Python (Data Science)',
    'R',
    'Pandas',
    'NumPy',
    'Matplotlib',
    'Seaborn',
    'Machine Learning',
    'Deep Learning',
    'TensorFlow',
    'PyTorch',
    'Big Data',
    'Hadoop',
    'Spark',
    'Kafka',
    'Data Warehousing',
    'ETL',
    'Business Intelligence',
    'Statistical Analysis',
    'Predictive Modeling',

    // DevOps и инфраструктура
    'DevOps',
    'Terraform',
    'Ansible',
    'Prometheus',
    'Grafana',
    'Splunk',
    'ELK Stack',
    'Nginx',
    'Apache',
    'Load Balancing',
    'Networking',
    'TCP/IP',
    'DNS',
    'VPN',
    'Firewalls',
    'Cybersecurity',
    'Penetration Testing',
    'Ethical Hacking',
    'OWASP',
    'Cryptography',
    'Blockchain Security',
    'Network Security',
    'Cloud Security',
    'AI/ML Security',

    // Тестирование и QA
    'Manual Testing',
    'Automated Testing',
    'Selenium',
    'Cypress',
    'Jest',
    'Mocha',
    'Chai',
    'Unit Testing',
    'Integration Testing',
    'End-to-End Testing',
    'Performance Testing',
    'Load Testing',
    'Security Testing',
    'Test Planning',
    'Bug Tracking',
    'JIRA (QA)',
    'Postman',
    'Swagger',
    'API Testing',

    // Другие IT-навыки
    'Blockchain',
    'Web3',
    'Solidity',
    'Smart Contracts',
    'IoT',
    'Raspberry Pi',
    'Arduino',
    'Electronics',
    'Unity',
    'Unreal Engine',
    'Game Development',
    'AR/VR',
    'Chatbots',
    'Natural Language Processing (NLP)',
    'Computer Vision',
    'Robotics',
    'Quantum Computing',

    // Мягкие навыки (Soft Skills)
    'Communication',
    'Teamwork',
    'Leadership',
    'Problem Solving',
    'Critical Thinking',
    'Time Management',
    'Adaptability',
    'Conflict Resolution',
    'Emotional Intelligence',
    'Negotiation',
    'Presentation Skills',
    'Public Speaking',
    'Mentoring',
    'Remote Work',
    'Cross-functional Collaboration',
];
